baseURL = "https://jimandreas.github.io/EmilieDuChatelet/"
languageCode = "en-us"
title = "Émilie du Châtelet · Selected Works"
theme = "minimal"

[markup]
  [markup.tableOfContents]
    endLevel = 4
    startLevel = 2
  [markup.highlight]
    style = "dracula"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
